version: '3.7'
services:
  chrome:
    image: seleniarm/node-chromium:latest
    build:
      context: .
      shm_size: 2gb
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_VNC_VIEW_ONLY=1
      - SE_VNC_NO_PASSWORD=1
      - TZ=Asia/Kolkata
  firefox:
    image: seleniarm/node-firefox:latest
    build:
      context: .
      shm_size: 2gb
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_VNC_VIEW_ONLY=1
      - SE_VNC_NO_PASSWORD=1
      - TZ=Asia/Kolkata
  selenium-hub:
    image: seleniarm/hub:latest
    container_name: selenium-hub
    environment:
      - SE_JAVA_OPTS=-Xmx512m
      - SE_OPTS=--allow-cors true
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"